### ISSUE TITLE
Add javascript libs required to use Availity Toolkit components

### ISSUE THREAD

**Issue by cornellb** [Availity/availity-toolkit#23]
Right now, we provide code snippets on how to use a given component but we dont specify what javascript libs are required for that & how to include them.

**Comment by robmcguinness** [comment]
this Toolkit is already setup to include all the necessary files for you:
- https://github.com/Availity/availity-toolkit/blob/master/project/app/index.js
- https://github.com/Availity/availity-toolkit/blob/master/project/app/vendor.js

Please reopen if I misunderstood.
